// Generated by satounki/common-gen

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

// Google Cloud Platform project configuration
type gcpProjectResourceData struct {
	// Time of the last modification to this resource
	LastUpdated types.String `tfsdk:"last_updated" rustdoc:"Time of the last modification to this resource" resourcedoc:"Google Cloud Platform project configuration"`
	// UUID generated by Satounki
	ID types.String `tfsdk:"id" rustdoc:"UUID generated by Satounki" resourcedoc:"Google Cloud Platform project configuration"`
	// Meaningful alias for the project to be used by Satounki users
	Project types.String `tfsdk:"project" rustdoc:"Meaningful alias for the project to be used by Satounki users" resourcedoc:"Google Cloud Platform project configuration"`
	// Number of approvals required for access requests made to the project
	ApprovalsRequired types.Int64 `tfsdk:"approvals_required" rustdoc:"Number of approvals required for access requests made to the project" resourcedoc:"Google Cloud Platform project configuration"`
	// Require additional approval by an Administrator for access requests made to the project
	AdminApprovalRequired types.Bool `tfsdk:"admin_approval_required" rustdoc:"Require additional approval by an Administrator for access requests made to the project" resourcedoc:"Google Cloud Platform project configuration"`
}
