// Generated by satounki/common-gen

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

// Service-specific username aliases
type userAliasesResourceData struct {
	// Time of the last modification to this resource
	LastUpdated types.String `tfsdk:"last_updated" rustdoc:"Time of the last modification to this resource" resourcedoc:"Service-specific username aliases"`
	// Terraform-generated resource ID
	ID types.String `tfsdk:"id" rustdoc:"Terraform-generated resource ID" resourcedoc:"Service-specific username aliases"`
	// Email address registered with Satounki
	Email types.String `tfsdk:"email" rustdoc:"Email address registered with Satounki" resourcedoc:"Service-specific username aliases"`
	// Username on Amazon Web Services, may not be an email address
	Aws types.String `tfsdk:"aws" rustdoc:"Username on Amazon Web Services, may not be an email address" resourcedoc:"Service-specific username aliases"`
	// Email address registered with Cloudflare
	Cloudflare types.String `tfsdk:"cloudflare" rustdoc:"Email address registered with Cloudflare" resourcedoc:"Service-specific username aliases"`
	// Email address registered with Google Cloud Platform
	Gcp types.String `tfsdk:"gcp" rustdoc:"Email address registered with Google Cloud Platform" resourcedoc:"Service-specific username aliases"`
}
