// Generated by satounki/common-gen

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

// Satounki user access roles
type userRolesResourceData struct {
	// Time of the last modification to this resource
	LastUpdated types.String `tfsdk:"last_updated" rustdoc:"Time of the last modification to this resource" resourcedoc:"Satounki user access roles"`
	// Terraform-generated resource ID
	ID types.String `tfsdk:"id" rustdoc:"Terraform-generated resource ID"`
	// Email address registered with Satounki
	Email types.String `tfsdk:"email" rustdoc:"Email address registered with Satounki" resourcedoc:"Satounki user access roles"`
	// Access roles
	AccessRoles []types.String `tfsdk:"access_roles" rustdoc:"Access roles" resourcedoc:"Satounki user access roles"`
}
