pub use delete::*;
pub use get_id::*;
pub use get_list::*;
pub use patch_id::*;
pub use patch_id_body::*;
pub use post::*;
pub use post_id::*;
pub use put::*;
pub use put_id::*;
pub use put_id_body::*;

mod delete;
mod get_id;
mod get_list;
mod patch_id;
mod patch_id_body;
mod post;
mod post_id;
mod put;
mod put_id;
mod put_id_body;

pub const TERRAFORM_RESOURCE: &str = r#"// Generated by satounki/common-gen

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

// {{ doc }}
type {{ name|camel }}ResourceData struct {
    {{ members }}
}
"#;
