use common_macros::route_request_response;

use crate::AwsPolicy;
use crate::CloudflareRole;
use crate::GcpRole;
use crate::New;
use crate::Schema;
use crate::Terraform;

/// Satounki Policy definition
#[apply(New!)]
#[apply(Terraform!)]
#[apply(Schema!)]
pub struct Policy {
    /// UUID generated by Satounki
    #[schema(example = "5da0230c-4eeb-4840-9ffa-d97f45a12182")]
    pub id: String,
    /// Succinct, descriptive name for the policy in snake_case
    #[schema(example = "compute_dns_admin")]
    pub name: String,
    /// Description of the permissions granted by this policy
    #[schema(
        example = "Admin access to AWS and GCP compute resources, and Cloudflare DNS resources"
    )]
    pub description: String,
    /// Google Cloud Platform roles associated with this policy
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gcp: Option<Vec<GcpRole>>,
    /// Amazon Web Services policy ARNs associated with this policy
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aws: Option<Vec<AwsPolicy>>,
    /// Cloudflare roles associated with this policy
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cloudflare: Option<Vec<CloudflareRole>>,
}

route_request_response! {
    #[Put]  Policy(NewPolicy) -> Policy,
    #[Post] Policy(NewPolicy) -> Policy,
    #[Get]  Policy() -> Policy,
    #[Get]  PolicyName() -> Policy,
    #[Get]  Policies() -> Vec<Policy>,
}
