// Generated by satounki/common-gen

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

// Company
type companyResourceData struct {
	// Time of the last modification to this resource
	LastUpdated types.String `tfsdk:"last_updated" rustdoc:"Time of the last modification to this resource" resourcedoc:"Company"`
	// Auto-incrementing integer
	ID types.String `tfsdk:"id" rustdoc:"Auto-incrementing integer" resourcedoc:"Company"`
	// Name of the company
	Name types.String `tfsdk:"name" rustdoc:"Name of the company" resourcedoc:"Company"`
	// Email domain of the company (G-Suite etc.)
	Domain types.String `tfsdk:"domain" rustdoc:"Email domain of the company (G-Suite etc.)" resourcedoc:"Company"`
	// Company root user's email address
	RootUserEmail types.String `tfsdk:"root_user_email" rustdoc:"Company root user's email address" resourcedoc:"Company"`
	// Company root user's first name
	RootUserFirstName types.String `tfsdk:"root_user_first_name" rustdoc:"Company root user's first name" resourcedoc:"Company"`
	// Company root user's last name
	RootUserLastName types.String `tfsdk:"root_user_last_name" rustdoc:"Company root user's last name" resourcedoc:"Company"`
	// Company API token
	ApiToken types.String `tfsdk:"api_token" rustdoc:"Company API token" resourcedoc:"Company"`
	// Company worker key
	WorkerKey types.String `tfsdk:"worker_key" rustdoc:"Company worker key" resourcedoc:"Company"`
}
